/**
 * レート戦の対戦相手の名簿（120人：Lv1〜10に12人ずつ）。名前ごとにLv・性格・得意デッキが決まっている。
 * 名前から戦い方は分からないようにしている。性格は判断の重みと得意デッキだけを変え、読みの深さ（＝Lvの強さ）は変えない。
 * 各Lvの内訳：攻め型4・守り型2・策士型4・堅実型2。
 * デッキ：Lv1〜3は弱め、Lv4〜7は普通〜やや強め、Lv8〜10は環境デッキ。deck / sub は src/sim/metaDecks.ts と set2Decks.ts の id。
 * 第2弾のデッキ（g_*）がメインの相手は、第2弾の配信まではサブを使う。
 * NOT IN THE GAME YET: the rated mode still uses RATED_FOES and PLAYER_NAMES (src/meta/rating.ts).
 */
export type Persona = 'attack' | 'guard' | 'schemer' | 'steady';
export const PERSONA_NAMES: Record<Persona, string> = { attack: '攻め型', guard: '守り型', schemer: '策士型', steady: '堅実型' };
export interface Rival { name: string; lv: number; rating: number; persona: Persona; deck: string; sub: string }
/** Lvごとの目安レート（Lv10は2000〜）。 */
export const LV_RATING = [1000, 1100, 1200, 1300, 1400, 1500, 1600, 1730, 1860, 2000];
export const ROSTER: Rival[] = [
  {name: "たっくん",lv: 1,rating: 965,persona: "attack",deck: "rush",sub: "g_mid"},
  {name: "二度寝の刻",lv: 1,rating: 1010,persona: "attack",deck: "g_mid",sub: "rush"},
  {name: "nekoyama",lv: 1,rating: 1030,persona: "attack",deck: "rush",sub: "g_mid"},
  {name: "今日こそ勝つ",lv: 1,rating: 980,persona: "attack",deck: "g_mid",sub: "rush"},
  {name: "みーこ",lv: 1,rating: 1040,persona: "guard",deck: "titan",sub: "g_quiet"},
  {name: "目覚まし3回目",lv: 1,rating: 995,persona: "guard",deck: "p_titan",sub: "titan"},
  {name: "ゆっきー",lv: 1,rating: 1025,persona: "schemer",deck: "oracle",sub: "g_quiet"},
  {name: "腹時計",lv: 1,rating: 970,persona: "schemer",deck: "g_quiet",sub: "oracle"},
  {name: "mii_mii",lv: 1,rating: 1000,persona: "schemer",deck: "oracle",sub: "g_quiet"},
  {name: "ノリで来た",lv: 1,rating: 1015,persona: "schemer",deck: "g_quiet",sub: "oracle"},
  {name: "ぽんちゃん",lv: 1,rating: 985,persona: "steady",deck: "balance",sub: "g_mid"},
  {name: "昼寝のプロ",lv: 1,rating: 1035,persona: "steady",deck: "g_mid",sub: "balance"},
  {name: "もっちー",lv: 2,rating: 1065,persona: "attack",deck: "g_mid",sub: "rush"},
  {name: "時差ボケ太郎",lv: 2,rating: 1110,persona: "attack",deck: "rush",sub: "g_mid"},
  {name: "yuzu.p",lv: 2,rating: 1130,persona: "attack",deck: "g_mid",sub: "rush"},
  {name: "本気出すのは明日",lv: 2,rating: 1080,persona: "attack",deck: "rush",sub: "g_mid"},
  {name: "三日坊主",lv: 2,rating: 1140,persona: "guard",deck: "p_titan",sub: "titan"},
  {name: "まるちゃん",lv: 2,rating: 1095,persona: "guard",deck: "titan",sub: "g_quiet"},
  {name: "sakana_9",lv: 2,rating: 1125,persona: "schemer",deck: "g_quiet",sub: "oracle"},
  {name: "ガチ勢見習い",lv: 2,rating: 1070,persona: "schemer",deck: "oracle",sub: "g_quiet"},
  {name: "りっちゃん",lv: 2,rating: 1100,persona: "schemer",deck: "g_quiet",sub: "oracle"},
  {name: "朝ごはん抜き",lv: 2,rating: 1115,persona: "schemer",deck: "oracle",sub: "g_quiet"},
  {name: "けんけん",lv: 2,rating: 1085,persona: "steady",deck: "g_mid",sub: "balance"},
  {name: "tora7",lv: 2,rating: 1135,persona: "steady",deck: "balance",sub: "g_mid"},
  {name: "あーちゃん",lv: 3,rating: 1165,persona: "attack",deck: "rush",sub: "g_mid"},
  {name: "遅刻魔王",lv: 3,rating: 1210,persona: "attack",deck: "g_mid",sub: "rush"},
  {name: "Haru_jp",lv: 3,rating: 1230,persona: "attack",deck: "rush",sub: "g_mid"},
  {name: "運だけで来た",lv: 3,rating: 1180,persona: "attack",deck: "g_mid",sub: "rush"},
  {name: "ひなっち",lv: 3,rating: 1240,persona: "guard",deck: "titan",sub: "g_quiet"},
  {name: "夏休みの宿題",lv: 3,rating: 1195,persona: "guard",deck: "p_titan",sub: "titan"},
  {name: "kenji1205",lv: 3,rating: 1225,persona: "schemer",deck: "oracle",sub: "g_quiet"},
  {name: "はるるん",lv: 3,rating: 1170,persona: "schemer",deck: "g_quiet",sub: "oracle"},
  {name: "5分前行動",lv: 3,rating: 1200,persona: "schemer",deck: "oracle",sub: "g_quiet"},
  {name: "手札事故の帝王",lv: 3,rating: 1215,persona: "schemer",deck: "g_quiet",sub: "oracle"},
  {name: "aoba_x",lv: 3,rating: 1185,persona: "steady",deck: "balance",sub: "g_mid"},
  {name: "そらっち",lv: 3,rating: 1235,persona: "steady",deck: "g_mid",sub: "balance"},
  {name: "定時退社",lv: 4,rating: 1265,persona: "attack",deck: "p_rush",sub: "g_maze"},
  {name: "よっしー",lv: 4,rating: 1310,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "ryu_44",lv: 4,rating: 1330,persona: "attack",deck: "g_maze",sub: "shadow"},
  {name: "一生カード引いてたい",lv: 4,rating: 1280,persona: "attack",deck: "antiv",sub: "p_rush"},
  {name: "かずぴ",lv: 4,rating: 1340,persona: "guard",deck: "charge",sub: "g_bells"},
  {name: "月曜の朝",lv: 4,rating: 1295,persona: "guard",deck: "g_bells",sub: "charge"},
  {name: "Rin.k",lv: 4,rating: 1325,persona: "schemer",deck: "p_echo",sub: "antiv"},
  {name: "実家のような安心感",lv: 4,rating: 1270,persona: "schemer",deck: "antiv",sub: "p_echo"},
  {name: "こーへー",lv: 4,rating: 1300,persona: "schemer",deck: "p_echo",sub: "g_bells"},
  {name: "終電ダッシュ",lv: 4,rating: 1315,persona: "schemer",deck: "antiv",sub: "p_echo"},
  {name: "mzk_0811",lv: 4,rating: 1285,persona: "steady",deck: "p_balance",sub: "g_maze"},
  {name: "なっつん",lv: 4,rating: 1335,persona: "steady",deck: "g_bells",sub: "p_balance"},
  {name: "締切前夜",lv: 5,rating: 1365,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "T.Kaz",lv: 5,rating: 1410,persona: "attack",deck: "p_rush",sub: "g_maze"},
  {name: "つっきー",lv: 5,rating: 1430,persona: "attack",deck: "antiv",sub: "p_rush"},
  {name: "最強の凡人",lv: 5,rating: 1380,persona: "attack",deck: "g_maze",sub: "shadow"},
  {name: "寝落ち常習犯",lv: 5,rating: 1440,persona: "guard",deck: "g_bells",sub: "charge"},
  {name: "natsu_rx",lv: 5,rating: 1395,persona: "guard",deck: "charge",sub: "g_bells"},
  {name: "まなりん",lv: 5,rating: 1425,persona: "schemer",deck: "antiv",sub: "p_echo"},
  {name: "時給950円",lv: 5,rating: 1370,persona: "schemer",deck: "p_echo",sub: "antiv"},
  {name: "akari22",lv: 5,rating: 1400,persona: "schemer",deck: "antiv",sub: "p_echo"},
  {name: "神引き待ち",lv: 5,rating: 1415,persona: "schemer",deck: "p_echo",sub: "g_bells"},
  {name: "しーくん",lv: 5,rating: 1385,persona: "steady",deck: "g_bells",sub: "p_balance"},
  {name: "体内時計バグ",lv: 5,rating: 1435,persona: "steady",deck: "p_balance",sub: "g_maze"},
  {name: "kaede_0",lv: 6,rating: 1465,persona: "attack",deck: "g_maze",sub: "shadow"},
  {name: "にっしー",lv: 6,rating: 1510,persona: "attack",deck: "p_rush",sub: "g_maze"},
  {name: "残業の申し子",lv: 6,rating: 1530,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "引退撤回3回目",lv: 6,rating: 1480,persona: "attack",deck: "antiv",sub: "p_rush"},
  {name: "ShunSK",lv: 6,rating: 1540,persona: "guard",deck: "charge",sub: "g_bells"},
  {name: "ちゃんみ",lv: 6,rating: 1495,persona: "guard",deck: "g_bells",sub: "charge"},
  {name: "勝ったら寝る",lv: 6,rating: 1525,persona: "schemer",deck: "p_echo",sub: "antiv"},
  {name: "umi_no_ko",lv: 6,rating: 1470,persona: "schemer",deck: "antiv",sub: "p_echo"},
  {name: "おさむん",lv: 6,rating: 1500,persona: "schemer",deck: "p_echo",sub: "g_bells"},
  {name: "理論値の人",lv: 6,rating: 1515,persona: "schemer",deck: "antiv",sub: "p_echo"},
  {name: "ゆうちゃん",lv: 6,rating: 1485,persona: "steady",deck: "p_balance",sub: "g_maze"},
  {name: "月末の残高",lv: 6,rating: 1535,persona: "steady",deck: "g_bells",sub: "p_balance"},
  {name: "hiroto_v2",lv: 7,rating: 1565,persona: "attack",deck: "p_rush",sub: "g_maze"},
  {name: "負けたら引退",lv: 7,rating: 1610,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "あっきー",lv: 7,rating: 1630,persona: "attack",deck: "g_maze",sub: "shadow"},
  {name: "Mochi_kun",lv: 7,rating: 1580,persona: "attack",deck: "antiv",sub: "p_rush"},
  {name: "世界一の負けず嫌い",lv: 7,rating: 1640,persona: "guard",deck: "charge",sub: "g_bells"},
  {name: "sora-lab",lv: 7,rating: 1595,persona: "guard",deck: "g_bells",sub: "charge"},
  {name: "徹夜明けの本気",lv: 7,rating: 1625,persona: "schemer",deck: "antiv",sub: "p_echo"},
  {name: "Nao.T",lv: 7,rating: 1570,persona: "schemer",deck: "p_echo",sub: "antiv"},
  {name: "ねむり姫(仮)",lv: 7,rating: 1600,persona: "schemer",deck: "antiv",sub: "p_echo"},
  {name: "yoshi_ta",lv: 7,rating: 1615,persona: "schemer",deck: "p_echo",sub: "g_bells"},
  {name: "優勝したい",lv: 7,rating: 1585,persona: "steady",deck: "p_balance",sub: "g_maze"},
  {name: "rkt_0",lv: 7,rating: 1635,persona: "steady",deck: "g_bells",sub: "p_balance"},
  {name: "蒼",lv: 8,rating: 1695,persona: "attack",deck: "p_rush",sub: "shadow"},
  {name: "kuro_93",lv: 8,rating: 1740,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "まだ本気じゃない",lv: 8,rating: 1760,persona: "attack",deck: "p_rush",sub: "shadow"},
  {name: "凛",lv: 8,rating: 1710,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "嶺",lv: 8,rating: 1770,persona: "guard",deck: "burn",sub: "lock"},
  {name: "休日出勤",lv: 8,rating: 1725,persona: "guard",deck: "burn",sub: "lock"},
  {name: "Orca",lv: 8,rating: 1755,persona: "schemer",deck: "lock",sub: "control"},
  {name: "akatsuki_s",lv: 8,rating: 1700,persona: "schemer",deck: "reso",sub: "lock"},
  {name: "朝まで一本勝負",lv: 8,rating: 1730,persona: "schemer",deck: "control",sub: "reso"},
  {name: "雅",lv: 8,rating: 1745,persona: "schemer",deck: "lock",sub: "reso"},
  {name: "ふーみん",lv: 8,rating: 1715,persona: "steady",deck: "control",sub: "burn"},
  {name: "負けイベント拒否",lv: 8,rating: 1765,persona: "steady",deck: "reso",sub: "control"},
  {name: "玄",lv: 9,rating: 1825,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "Vega",lv: 9,rating: 1870,persona: "attack",deck: "p_rush",sub: "shadow"},
  {name: "全国大会帰り",lv: 9,rating: 1890,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "tsubame_k",lv: 9,rating: 1840,persona: "attack",deck: "p_rush",sub: "shadow"},
  {name: "朧",lv: 9,rating: 1900,persona: "guard",deck: "burn",sub: "lock"},
  {name: "ラスボスの前座",lv: 9,rating: 1855,persona: "guard",deck: "burn",sub: "lock"},
  {name: "鴉",lv: 9,rating: 1885,persona: "schemer",deck: "reso",sub: "lock"},
  {name: "hayate.n",lv: 9,rating: 1830,persona: "schemer",deck: "lock",sub: "control"},
  {name: "有給消化中",lv: 9,rating: 1860,persona: "schemer",deck: "control",sub: "reso"},
  {name: "煌",lv: 9,rating: 1875,persona: "schemer",deck: "lock",sub: "reso"},
  {name: "ハル",lv: 9,rating: 1845,persona: "steady",deck: "reso",sub: "control"},
  {name: "勝率しか見てない",lv: 9,rating: 1895,persona: "steady",deck: "control",sub: "burn"},
  {name: "Ace",lv: 10,rating: 2040,persona: "attack",deck: "p_rush",sub: "shadow"},
  {name: "櫻",lv: 10,rating: 2070,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "零",lv: 10,rating: 2020,persona: "attack",deck: "p_rush",sub: "shadow"},
  {name: "zenith_k",lv: 10,rating: 2100,persona: "attack",deck: "shadow",sub: "p_rush"},
  {name: "刹那",lv: 10,rating: 2060,persona: "guard",deck: "burn",sub: "lock"},
  {name: "無敗の二番手",lv: 10,rating: 2090,persona: "guard",deck: "burn",sub: "lock"},
  {name: "黎明",lv: 10,rating: 2150,persona: "schemer",deck: "verna",sub: "lock"},
  {name: "Noir",lv: 10,rating: 2120,persona: "schemer",deck: "verna",sub: "reso"},
  {name: "seiryu_x",lv: 10,rating: 2110,persona: "schemer",deck: "lock",sub: "control"},
  {name: "時間外労働",lv: 10,rating: 2130,persona: "schemer",deck: "reso",sub: "control"},
  {name: "天",lv: 10,rating: 2080,persona: "steady",deck: "control",sub: "burn"},
  {name: "神様の暇つぶし",lv: 10,rating: 2140,persona: "steady",deck: "reso",sub: "control"},
];
