/**
 * レート戦の対戦相手の名簿（120人：Lv1〜10に12人ずつ）。名前ごとにLv・性格・得意デッキが決まっている。
 * 性格は判断の重みと得意デッキだけを変え、読みの深さ（＝Lvの強さ）は変えない。
 * 各Lvの内訳：攻め型4・守り型2・策士型4・堅実型2。deck / sub は環境デッキ（src/sim/metaDecks.ts）の id。
 * NOT IN THE GAME YET: the rated mode still uses RATED_FOES and PLAYER_NAMES (src/meta/rating.ts).
 */
export type Persona = 'attack' | 'guard' | 'schemer' | 'steady';
export const PERSONA_NAMES: Record<Persona, string> = { attack: '攻め型', guard: '守り型', schemer: '策士型', steady: '堅実型' };
export interface Rival { name: string; lv: number; rating: number; persona: Persona; deck: string; sub: string; line: string }
/** Lvごとの目安レート（Lv10は2000〜）。 */
export const LV_RATING = [1000, 1100, 1200, 1300, 1400, 1500, 1600, 1730, 1860, 2000];
export const ROSTER: Rival[] = [
  {name: "たかし",lv: 1,rating: 965,persona: "attack",deck: "rush",sub: "balance",line: "とりあえず殴る！"},
  {name: "ぽてと",lv: 1,rating: 1010,persona: "attack",deck: "rush",sub: "balance",line: "速いデッキが好き"},
  {name: "Ren",lv: 1,rating: 1030,persona: "attack",deck: "rush",sub: "titan",line: "最近始めました"},
  {name: "みけ",lv: 1,rating: 980,persona: "attack",deck: "rush",sub: "balance",line: "ねこは速い"},
  {name: "みなと",lv: 1,rating: 1040,persona: "guard",deck: "titan",sub: "balance",line: "港みたいにのんびり守る"},
  {name: "ゆずポン",lv: 1,rating: 995,persona: "guard",deck: "titan",sub: "balance",line: "壁を置けば安心"},
  {name: "しずく",lv: 1,rating: 1025,persona: "schemer",deck: "oracle",sub: "balance",line: "予約って面白い"},
  {name: "Mugi",lv: 1,rating: 970,persona: "schemer",deck: "oracle",sub: "rush",line: "カードの説明を読むのが好き"},
  {name: "こはる",lv: 1,rating: 1000,persona: "schemer",deck: "oracle",sub: "balance",line: "未来が見てみたい"},
  {name: "すず",lv: 1,rating: 1015,persona: "schemer",deck: "oracle",sub: "titan",line: "鐘の音が好き"},
  {name: "あおい",lv: 1,rating: 985,persona: "steady",deck: "balance",sub: "rush",line: "まずは基本から"},
  {name: "ときのすけ",lv: 1,rating: 1035,persona: "steady",deck: "balance",sub: "titan",line: "よろしくお願いします"},
  {name: "しゅん",lv: 2,rating: 1065,persona: "attack",deck: "rush",sub: "balance",line: "先手必勝"},
  {name: "Kaito",lv: 2,rating: 1110,persona: "attack",deck: "rush",sub: "balance",line: "攻めてなんぼ"},
  {name: "はやて",lv: 2,rating: 1130,persona: "attack",deck: "rush",sub: "titan",line: "風のように駆け抜ける"},
  {name: "Taku",lv: 2,rating: 1080,persona: "attack",deck: "rush",sub: "balance",line: "早く終わらせたい派"},
  {name: "たまご",lv: 2,rating: 1140,persona: "guard",deck: "titan",sub: "balance",line: "割れないように守る"},
  {name: "ねこまる",lv: 2,rating: 1095,persona: "guard",deck: "titan",sub: "oracle",line: "こたつで籠城"},
  {name: "ことは",lv: 2,rating: 1125,persona: "schemer",deck: "oracle",sub: "balance",line: "言葉より予約"},
  {name: "Mei",lv: 2,rating: 1070,persona: "schemer",deck: "oracle",sub: "balance",line: "時計をよく見てます"},
  {name: "いぶき",lv: 2,rating: 1100,persona: "schemer",deck: "oracle",sub: "titan",line: "考える時間が好き"},
  {name: "ちひろ",lv: 2,rating: 1115,persona: "schemer",deck: "oracle",sub: "rush",line: "読み合いを勉強中"},
  {name: "Shiro",lv: 2,rating: 1085,persona: "steady",deck: "balance",sub: "titan",line: "堅実第一"},
  {name: "Haru",lv: 2,rating: 1135,persona: "steady",deck: "balance",sub: "rush",line: "バランスが大事"},
  {name: "ひなた",lv: 3,rating: 1165,persona: "attack",deck: "rush",sub: "balance",line: "明るく攻める"},
  {name: "Ryo",lv: 3,rating: 1210,persona: "attack",deck: "rush",sub: "balance",line: "一気に決める"},
  {name: "あかね",lv: 3,rating: 1230,persona: "attack",deck: "rush",sub: "titan",line: "夕方までには終わらせる"},
  {name: "だいち",lv: 3,rating: 1180,persona: "attack",deck: "rush",sub: "balance",line: "力押しが得意"},
  {name: "かべ職人",lv: 3,rating: 1240,persona: "guard",deck: "titan",sub: "balance",line: "壁は芸術"},
  {name: "まっちゃ",lv: 3,rating: 1195,persona: "guard",deck: "titan",sub: "oracle",line: "渋く守る"},
  {name: "yuu",lv: 3,rating: 1225,persona: "schemer",deck: "oracle",sub: "balance",line: "予約は2つまで、覚えた"},
  {name: "つむぎ",lv: 3,rating: 1170,persona: "schemer",deck: "oracle",sub: "titan",line: "糸を紡ぐように詰める"},
  {name: "Aki",lv: 3,rating: 1200,persona: "schemer",deck: "oracle",sub: "balance",line: "秋の夜長に読み合い"},
  {name: "のぞみ",lv: 3,rating: 1215,persona: "schemer",deck: "oracle",sub: "rush",line: "望みは最後の予約に"},
  {name: "けいた",lv: 3,rating: 1185,persona: "steady",deck: "balance",sub: "rush",line: "普通が一番"},
  {name: "Natsu",lv: 3,rating: 1235,persona: "steady",deck: "balance",sub: "titan",line: "夏休みに始めました"},
  {name: "一撃屋",lv: 4,rating: 1265,persona: "attack",deck: "p_rush",sub: "rush",line: "一撃で決める"},
  {name: "Sora",lv: 4,rating: 1310,persona: "attack",deck: "rush",sub: "p_rush",line: "空いたレーンを狙え"},
  {name: "ゆうと",lv: 4,rating: 1330,persona: "attack",deck: "p_rush",sub: "rush",line: "急襲が好き"},
  {name: "はぐるま",lv: 4,rating: 1280,persona: "attack",deck: "rush",sub: "p_rush",line: "回るように殴る"},
  {name: "盾持ち",lv: 4,rating: 1340,persona: "guard",deck: "p_titan",sub: "titan",line: "守って勝つ"},
  {name: "さくら",lv: 4,rating: 1295,persona: "guard",deck: "titan",sub: "p_titan",line: "散らない城"},
  {name: "予約魔",lv: 4,rating: 1325,persona: "schemer",deck: "oracle",sub: "p_echo",line: "予約しないと落ち着かない"},
  {name: "ruri",lv: 4,rating: 1270,persona: "schemer",deck: "p_echo",sub: "oracle",line: "残響が聞こえる"},
  {name: "かなで",lv: 4,rating: 1300,persona: "schemer",deck: "p_echo",sub: "oracle",line: "響きを重ねる"},
  {name: "Kei",lv: 4,rating: 1315,persona: "schemer",deck: "oracle",sub: "p_echo",line: "先を読む練習中"},
  {name: "そうま",lv: 4,rating: 1285,persona: "steady",deck: "balance",sub: "p_balance",line: "無理はしない"},
  {name: "Tomo",lv: 4,rating: 1335,persona: "steady",deck: "p_balance",sub: "balance",line: "勝率5割を目指す"},
  {name: "秒針マニア",lv: 5,rating: 1365,persona: "attack",deck: "rush",sub: "p_rush",line: "1刻も無駄にしない"},
  {name: "Hikaru7",lv: 5,rating: 1410,persona: "attack",deck: "p_rush",sub: "rush",line: "光の速さで"},
  {name: "つばさ",lv: 5,rating: 1430,persona: "attack",deck: "p_rush",sub: "rush",line: "飛ばしていく"},
  {name: "Rei_0423",lv: 5,rating: 1380,persona: "attack",deck: "rush",sub: "p_rush",line: "攻めは最大の防御"},
  {name: "鉄壁",lv: 5,rating: 1440,persona: "guard",deck: "p_titan",sub: "titan",line: "ここは通さない"},
  {name: "こよみ",lv: 5,rating: 1395,persona: "guard",deck: "titan",sub: "p_titan",line: "暦をめくるように長期戦"},
  {name: "時計いじり",lv: 5,rating: 1425,persona: "schemer",deck: "oracle",sub: "p_echo",line: "相手の時計を進めるのが仕事"},
  {name: "あまね",lv: 5,rating: 1370,persona: "schemer",deck: "p_echo",sub: "oracle",line: "全部見えてる"},
  {name: "Minato_R",lv: 5,rating: 1400,persona: "schemer",deck: "oracle",sub: "p_echo",line: "読み勝ちが一番気持ちいい"},
  {name: "かげろう",lv: 5,rating: 1415,persona: "schemer",deck: "p_echo",sub: "oracle",line: "影からこっそり"},
  {name: "歯車好き",lv: 5,rating: 1385,persona: "steady",deck: "p_balance",sub: "balance",line: "噛み合えば勝てる"},
  {name: "Yuki_K",lv: 5,rating: 1435,persona: "steady",deck: "balance",sub: "p_balance",line: "手堅くいきます"},
  {name: "Kanata",lv: 6,rating: 1465,persona: "attack",deck: "p_rush",sub: "rush",line: "彼方まで突き抜ける"},
  {name: "ゼンマイ",lv: 6,rating: 1510,persona: "attack",deck: "rush",sub: "p_rush",line: "巻いたら止まらない"},
  {name: "りんご飴",lv: 6,rating: 1530,persona: "attack",deck: "p_rush",sub: "rush",line: "甘くないよ"},
  {name: "ろっく",lv: 6,rating: 1480,persona: "attack",deck: "rush",sub: "p_rush",line: "ロックに攻める"},
  {name: "城主",lv: 6,rating: 1540,persona: "guard",deck: "p_titan",sub: "titan",line: "この城は落ちない"},
  {name: "しぐれ",lv: 6,rating: 1495,persona: "guard",deck: "titan",sub: "p_titan",line: "時雨のように粘る"},
  {name: "針止め",lv: 6,rating: 1525,persona: "schemer",deck: "oracle",sub: "p_echo",line: "その一手、遅らせます"},
  {name: "ほたる",lv: 6,rating: 1470,persona: "schemer",deck: "p_echo",sub: "oracle",line: "光るのは最後"},
  {name: "Nao",lv: 6,rating: 1500,persona: "schemer",deck: "oracle",sub: "p_echo",line: "予約は嘘をつかない"},
  {name: "こまち",lv: 6,rating: 1515,persona: "schemer",deck: "p_echo",sub: "oracle",line: "待つのも戦略"},
  {name: "あらた",lv: 6,rating: 1485,persona: "steady",deck: "p_balance",sub: "balance",line: "基本を極める"},
  {name: "nagi",lv: 6,rating: 1535,persona: "steady",deck: "balance",sub: "p_balance",line: "凪のように"},
  {name: "突撃ラッパ",lv: 7,rating: 1565,persona: "attack",deck: "p_rush",sub: "rush",line: "全軍、前へ"},
  {name: "Riku",lv: 7,rating: 1610,persona: "attack",deck: "rush",sub: "p_rush",line: "足で勝つ"},
  {name: "mochi",lv: 7,rating: 1630,persona: "attack",deck: "p_rush",sub: "rush",line: "よく伸びる攻め"},
  {name: "ひろと",lv: 7,rating: 1580,persona: "attack",deck: "rush",sub: "p_rush",line: "速攻こそ正義"},
  {name: "とうま",lv: 7,rating: 1640,persona: "guard",deck: "p_titan",sub: "titan",line: "長期戦なら負けない"},
  {name: "ふゆ",lv: 7,rating: 1595,persona: "guard",deck: "titan",sub: "p_titan",line: "冬を越える備え"},
  {name: "刻の旅人",lv: 7,rating: 1625,persona: "schemer",deck: "p_echo",sub: "oracle",line: "時間は味方"},
  {name: "みずき",lv: 7,rating: 1570,persona: "schemer",deck: "oracle",sub: "p_echo",line: "水面下で準備中"},
  {name: "Zen",lv: 7,rating: 1600,persona: "schemer",deck: "p_echo",sub: "oracle",line: "静かに詰める"},
  {name: "くるみ",lv: 7,rating: 1615,persona: "schemer",deck: "oracle",sub: "p_echo",line: "殻を割るのは最後"},
  {name: "均衡主義",lv: 7,rating: 1585,persona: "steady",deck: "p_balance",sub: "balance",line: "偏らないのが強さ"},
  {name: "Sei",lv: 7,rating: 1635,persona: "steady",deck: "balance",sub: "p_balance",line: "正攻法で"},
  {name: "Tock",lv: 8,rating: 1695,persona: "attack",deck: "p_rush",sub: "rush",line: "秒で終わらせる"},
  {name: "はるか",lv: 8,rating: 1740,persona: "attack",deck: "shadow",sub: "p_rush",line: "遥か先へ"},
  {name: "あさぎ",lv: 8,rating: 1760,persona: "attack",deck: "antiv",sub: "p_rush",line: "ヴェルナ対策ならおまかせ"},
  {name: "シン",lv: 8,rating: 1710,persona: "attack",deck: "rush",sub: "shadow",line: "速攻の申し子"},
  {name: "れん",lv: 8,rating: 1770,persona: "guard",deck: "burn",sub: "p_titan",line: "じわじわ焼く"},
  {name: "石垣",lv: 8,rating: 1725,persona: "guard",deck: "p_titan",sub: "charge",line: "積み上げて守る"},
  {name: "kuro",lv: 8,rating: 1755,persona: "schemer",deck: "control",sub: "lock",line: "黒い予約に気をつけて"},
  {name: "策略家K",lv: 8,rating: 1700,persona: "schemer",deck: "lock",sub: "control",line: "三手先まで読んでる"},
  {name: "夜更かしP",lv: 8,rating: 1730,persona: "schemer",deck: "reso",sub: "p_echo",line: "夜更かしして研究中"},
  {name: "チクタク",lv: 8,rating: 1745,persona: "schemer",deck: "p_echo",sub: "reso",line: "時計の音、聞こえる？"},
  {name: "いつもの人",lv: 8,rating: 1715,persona: "steady",deck: "p_balance",sub: "balance",line: "いつものデッキで"},
  {name: "まんなか",lv: 8,rating: 1765,persona: "steady",deck: "balance",sub: "p_balance",line: "真ん中から崩す"},
  {name: "Clockwork",lv: 9,rating: 1825,persona: "attack",deck: "p_rush",sub: "antiv",line: "狂いなく攻める"},
  {name: "Ao",lv: 9,rating: 1870,persona: "attack",deck: "shadow",sub: "p_rush",line: "青い炎"},
  {name: "はやぶさ",lv: 9,rating: 1890,persona: "attack",deck: "p_rush",sub: "shadow",line: "最速で拠点へ"},
  {name: "Kaze",lv: 9,rating: 1840,persona: "attack",deck: "antiv",sub: "shadow",line: "追い風に乗る"},
  {name: "要塞",lv: 9,rating: 1900,persona: "guard",deck: "charge",sub: "burn",line: "崩せるものなら"},
  {name: "あまだれ",lv: 9,rating: 1855,persona: "guard",deck: "burn",sub: "charge",line: "雨垂れ石を穿つ"},
  {name: "しずか",lv: 9,rating: 1885,persona: "schemer",deck: "lock",sub: "control",line: "静かな牢獄へようこそ"},
  {name: "Yoru",lv: 9,rating: 1830,persona: "schemer",deck: "reso",sub: "lock",line: "夜は長い"},
  {name: "とき",lv: 9,rating: 1860,persona: "schemer",deck: "control",sub: "reso",line: "時を支配する"},
  {name: "つきよ",lv: 9,rating: 1875,persona: "schemer",deck: "lock",sub: "reso",line: "月夜の読み合い"},
  {name: "ちとせ",lv: 9,rating: 1845,persona: "steady",deck: "p_balance",sub: "balance",line: "千年たっても崩れない"},
  {name: "Hal",lv: 9,rating: 1895,persona: "steady",deck: "balance",sub: "p_balance",line: "穴のない構築"},
  {name: "迅雷",lv: 10,rating: 2040,persona: "attack",deck: "p_rush",sub: "shadow",line: "雷より速く"},
  {name: "ジン",lv: 10,rating: 2070,persona: "attack",deck: "shadow",sub: "p_rush",line: "止まったら負け"},
  {name: "Ace",lv: 10,rating: 2020,persona: "attack",deck: "p_rush",sub: "shadow",line: "先手で終わらせる"},
  {name: "かえで",lv: 10,rating: 2100,persona: "attack",deck: "shadow",sub: "p_rush",line: "散り際まで攻め続ける"},
  {name: "不落",lv: 10,rating: 2060,persona: "guard",deck: "burn",sub: "charge",line: "まだ誰にも落とされていない"},
  {name: "いわお",lv: 10,rating: 2090,persona: "guard",deck: "charge",sub: "burn",line: "動かざること山の如し"},
  {name: "終焉の鐘",lv: 10,rating: 2150,persona: "schemer",deck: "verna",sub: "reso",line: "この鐘が鳴ったら、終わり"},
  {name: "時の番人",lv: 10,rating: 2120,persona: "schemer",deck: "lock",sub: "control",line: "あなたの時計は、もう私のもの"},
  {name: "ミラ",lv: 10,rating: 2110,persona: "schemer",deck: "reso",sub: "lock",line: "響きは何度でも"},
  {name: "Noir",lv: 10,rating: 2130,persona: "schemer",deck: "control",sub: "lock",line: "約束は破るためにある"},
  {name: "天秤",lv: 10,rating: 2080,persona: "steady",deck: "p_balance",sub: "control",line: "どんな相手にも五分以上"},
  {name: "さくや",lv: 10,rating: 2140,persona: "steady",deck: "p_balance",sub: "p_rush",line: "隙を見せたら、そこで終わり"},
];
