/* Generated by `npm run wiki:stats` — do not edit by hand. AI「ふつう」同士の対戦結果。 */
export const STATS: {
  date: string; games: number; perPair: number;
  win: Record<string, number>; use: Record<string, [number, number]>;
  decks: string[]; matrix: Record<string, number[]>;
} = {
  "date": "2026-09-30",
  "games": 6400,
  "perPair": 100,
  "win": {
    "heavy": 50,
    "scout": 43,
    "scribe": 51,
    "arrow": 50,
    "cage": 46,
    "pendulum": 48,
    "gear": 47,
    "bolt": 43,
    "lancer": 51,
    "archer": 47,
    "warden": 48,
    "delayer": 49,
    "collapse": 54,
    "insight": 49,
    "dragon": 51,
    "haste": 40,
    "sentinel": 50,
    "ghost": 46,
    "rewind": 51,
    "breaker": 52,
    "titan": 60,
    "stop": 50,
    "oracle": 45,
    "e_verna": 54,
    "e_shot": 56,
    "e_bellkeeper": 54,
    "e_tuner": 52,
    "e_draw": 51,
    "e_march": 52,
    "e_sprite": 52,
    "e_twin": 53,
    "e_atra": 55,
    "e_mage": 53,
    "e_eternal": 46,
    "e_storm": 59,
    "e_pray": 53,
    "e_blade": 43,
    "e_reverse": 38,
    "e_page": 40,
    "e_raider": 44,
    "e_slash": 48,
    "e_guard": 50,
    "e_break": 53,
    "e_colossus": 57
  },
  "use": {
    "archer": [
      0.91,
      0
    ],
    "heavy": [
      0.72,
      0
    ],
    "pendulum": [
      1.24,
      0
    ],
    "scout": [
      1.02,
      0
    ],
    "arrow": [
      0.68,
      0.73
    ],
    "scribe": [
      0.63,
      0
    ],
    "warden": [
      0.51,
      0
    ],
    "cage": [
      0,
      0.66
    ],
    "bolt": [
      0.89,
      0.06
    ],
    "gear": [
      1.54,
      0
    ],
    "delayer": [
      0.56,
      0
    ],
    "lancer": [
      0.49,
      0
    ],
    "collapse": [
      0.35,
      0.25
    ],
    "insight": [
      0,
      0.11
    ],
    "dragon": [
      0.38,
      0
    ],
    "haste": [
      0.2,
      0.19
    ],
    "sentinel": [
      0.21,
      0
    ],
    "ghost": [
      0.43,
      0
    ],
    "rewind": [
      0.16,
      0.07
    ],
    "breaker": [
      0.34,
      0
    ],
    "titan": [
      0.24,
      0
    ],
    "stop": [
      0,
      0.11
    ],
    "oracle": [
      0.11,
      0
    ],
    "e_verna": [
      0.12,
      0
    ],
    "e_shot": [
      0.14,
      0.09
    ],
    "e_bellkeeper": [
      0.22,
      0
    ],
    "e_tuner": [
      0.19,
      0
    ],
    "e_draw": [
      0.02,
      0.19
    ],
    "e_march": [
      0.23,
      0
    ],
    "e_sprite": [
      0.2,
      0
    ],
    "e_twin": [
      0.21,
      0
    ],
    "e_atra": [
      0.12,
      0
    ],
    "e_mage": [
      0.11,
      0
    ],
    "e_eternal": [
      0.12,
      0.01
    ],
    "e_storm": [
      0.07,
      0.04
    ],
    "e_pray": [
      0.25,
      0.1
    ],
    "e_blade": [
      0.23,
      0
    ],
    "e_reverse": [
      0,
      0.1
    ],
    "e_page": [
      0.21,
      0
    ],
    "e_raider": [
      0.22,
      0
    ],
    "e_slash": [
      0.18,
      0.05
    ],
    "e_guard": [
      0.22,
      0
    ],
    "e_break": [
      0.03,
      0.02
    ],
    "e_colossus": [
      0.24,
      0
    ]
  },
  "decks": [
    "均衡の刻",
    "秒針突撃",
    "永劫の城塞",
    "予言の書架",
    "残響",
    "急襲",
    "均衡+",
    "城塞+"
  ],
  "matrix": {
    "均衡の刻": [
      50,
      52,
      42,
      55,
      40,
      59,
      49,
      36
    ],
    "秒針突撃": [
      48,
      45,
      48,
      65,
      42,
      56,
      48,
      42
    ],
    "永劫の城塞": [
      47,
      67,
      54,
      55,
      45,
      55,
      50,
      61
    ],
    "予言の書架": [
      45,
      52,
      52,
      48,
      57,
      49,
      40,
      45
    ],
    "残響": [
      53,
      52,
      61,
      55,
      45,
      51,
      56,
      49
    ],
    "急襲": [
      34,
      45,
      35,
      46,
      47,
      53,
      35,
      37
    ],
    "均衡+": [
      48,
      61,
      46,
      53,
      45,
      58,
      51,
      46
    ],
    "城塞+": [
      60,
      58,
      56,
      54,
      51,
      63,
      53,
      54
    ]
  }
};
