/* Generated by `npm run wiki:stats` — do not edit by hand. AI「ふつう」同士の対戦結果。 */
export const STATS: {
  date: string; games: number; perPair: number;
  win: Record<string, number>; use: Record<string, [number, number]>;
  decks: string[]; matrix: Record<string, number[]>;
} = {
  "date": "2026-09-30",
  "games": 6400,
  "perPair": 100,
  "win": {
    "heavy": 49,
    "scout": 44,
    "scribe": 50,
    "arrow": 51,
    "cage": 45,
    "pendulum": 46,
    "bolt": 43,
    "gear": 47,
    "lancer": 51,
    "archer": 47,
    "warden": 43,
    "delayer": 50,
    "collapse": 56,
    "insight": 47,
    "dragon": 51,
    "haste": 43,
    "sentinel": 50,
    "ghost": 48,
    "rewind": 52,
    "breaker": 50,
    "titan": 59,
    "stop": 49,
    "oracle": 48,
    "e_verna": 55,
    "e_draw": 48,
    "e_shot": 57,
    "e_bellkeeper": 53,
    "e_march": 51,
    "e_sprite": 53,
    "e_twin": 53,
    "e_tuner": 50,
    "e_atra": 56,
    "e_mage": 47,
    "e_eternal": 50,
    "e_storm": 60,
    "e_pray": 47,
    "e_blade": 48,
    "e_reverse": 43,
    "e_page": 45,
    "e_raider": 49,
    "e_slash": 52,
    "e_guard": 46,
    "e_break": 38,
    "e_colossus": 52
  },
  "use": {
    "archer": [
      0.88,
      0
    ],
    "heavy": [
      0.71,
      0
    ],
    "pendulum": [
      1.2,
      0
    ],
    "scout": [
      0.97,
      0
    ],
    "arrow": [
      0.68,
      0.68
    ],
    "scribe": [
      0.62,
      0
    ],
    "warden": [
      0.46,
      0
    ],
    "cage": [
      0,
      0.64
    ],
    "gear": [
      1.49,
      0
    ],
    "bolt": [
      0.85,
      0.08
    ],
    "delayer": [
      0.55,
      0
    ],
    "lancer": [
      0.48,
      0
    ],
    "collapse": [
      0.33,
      0.26
    ],
    "insight": [
      0,
      0.11
    ],
    "dragon": [
      0.37,
      0
    ],
    "haste": [
      0.19,
      0.18
    ],
    "sentinel": [
      0.2,
      0
    ],
    "ghost": [
      0.41,
      0
    ],
    "rewind": [
      0.16,
      0.07
    ],
    "breaker": [
      0.33,
      0
    ],
    "titan": [
      0.24,
      0
    ],
    "stop": [
      0,
      0.1
    ],
    "oracle": [
      0.11,
      0
    ],
    "e_verna": [
      0.12,
      0
    ],
    "e_draw": [
      0.02,
      0.19
    ],
    "e_shot": [
      0.14,
      0.09
    ],
    "e_bellkeeper": [
      0.22,
      0
    ],
    "e_march": [
      0.22,
      0
    ],
    "e_sprite": [
      0.2,
      0
    ],
    "e_twin": [
      0.21,
      0
    ],
    "e_tuner": [
      0.19,
      0
    ],
    "e_atra": [
      0.12,
      0
    ],
    "e_mage": [
      0.11,
      0
    ],
    "e_eternal": [
      0.11,
      0.02
    ],
    "e_storm": [
      0.07,
      0.04
    ],
    "e_pray": [
      0.22,
      0.1
    ],
    "e_blade": [
      0.22,
      0
    ],
    "e_reverse": [
      0,
      0.1
    ],
    "e_page": [
      0.2,
      0
    ],
    "e_raider": [
      0.21,
      0
    ],
    "e_slash": [
      0.19,
      0.04
    ],
    "e_guard": [
      0.22,
      0
    ],
    "e_break": [
      0,
      0.09
    ],
    "e_colossus": [
      0.23,
      0
    ]
  },
  "decks": [
    "均衡の刻",
    "秒針突撃",
    "永劫の城塞",
    "予言の書架",
    "残響",
    "急襲",
    "均衡+",
    "城塞+"
  ],
  "matrix": {
    "均衡の刻": [
      48,
      50,
      53,
      55,
      45,
      48,
      50,
      51
    ],
    "秒針突撃": [
      46,
      50,
      48,
      54,
      45,
      53,
      55,
      43
    ],
    "永劫の城塞": [
      49,
      66,
      57,
      53,
      45,
      60,
      53,
      55
    ],
    "予言の書架": [
      52,
      51,
      48,
      52,
      49,
      49,
      50,
      45
    ],
    "残響": [
      53,
      48,
      54,
      52,
      46,
      41,
      59,
      55
    ],
    "急襲": [
      43,
      53,
      41,
      51,
      40,
      48,
      34,
      53
    ],
    "均衡+": [
      55,
      61,
      38,
      60,
      53,
      52,
      48,
      51
    ],
    "城塞+": [
      55,
      56,
      45,
      56,
      39,
      52,
      54,
      53
    ]
  }
};
