/* Generated by `npm run wiki:stats` — do not edit by hand. AI「ふつう」同士の対戦結果。 */
export const STATS: {
  date: string; games: number; perPair: number;
  win: Record<string, number>; use: Record<string, [number, number]>;
  decks: string[]; matrix: Record<string, number[]>;
} = {
  "date": "2026-10-08",
  "games": 6400,
  "perPair": 64,
  "win": {
    "heavy": 49,
    "scout": 45,
    "scribe": 51,
    "arrow": 50,
    "cage": 47,
    "pendulum": 49,
    "gear": 48,
    "bolt": 44,
    "lancer": 52,
    "archer": 49,
    "warden": 48,
    "delayer": 51,
    "collapse": 52,
    "insight": 47,
    "dragon": 52,
    "ghost": 50,
    "haste": 43,
    "sentinel": 55,
    "rewind": 48,
    "titan": 60,
    "breaker": 52,
    "stop": 48,
    "oracle": 48,
    "e_bellkeeper": 51,
    "e_atra": 50,
    "e_shot": 54,
    "e_sprite": 51,
    "e_draw": 47,
    "e_mage": 53,
    "e_march": 52,
    "e_storm": 58,
    "e_eternal": 43,
    "e_pray": 49,
    "e_tuner": 50,
    "e_twin": 51,
    "e_verna": 50,
    "e_blade": 43,
    "e_raider": 44,
    "e_reverse": 41,
    "e_page": 41,
    "e_slash": 48,
    "e_break": 54,
    "e_guard": 49,
    "e_colossus": 53,
    "x_mirea": 46,
    "x_seer": 46,
    "x_decoy": 41,
    "x_gust": 46,
    "x_oblivion": 44,
    "x_ram": 44,
    "x_usurper": 46,
    "x_sentry": 45
  },
  "use": {
    "archer": [
      0.9,
      0
    ],
    "heavy": [
      0.95,
      0
    ],
    "pendulum": [
      0.97,
      0
    ],
    "scout": [
      0.95,
      0
    ],
    "arrow": [
      0.67,
      0.81
    ],
    "scribe": [
      0.57,
      0
    ],
    "warden": [
      0.64,
      0
    ],
    "cage": [
      0,
      0.51
    ],
    "bolt": [
      0.81,
      0.06
    ],
    "gear": [
      1.23,
      0
    ],
    "delayer": [
      0.56,
      0
    ],
    "lancer": [
      0.51,
      0
    ],
    "collapse": [
      0.42,
      0.29
    ],
    "insight": [
      0.01,
      0.18
    ],
    "dragon": [
      0.44,
      0
    ],
    "ghost": [
      0.34,
      0
    ],
    "haste": [
      0.15,
      0.14
    ],
    "sentinel": [
      0.16,
      0
    ],
    "rewind": [
      0.33,
      0.1
    ],
    "titan": [
      0.21,
      0
    ],
    "breaker": [
      0.29,
      0
    ],
    "stop": [
      0,
      0.09
    ],
    "oracle": [
      0.09,
      0
    ],
    "e_bellkeeper": [
      0.18,
      0
    ],
    "e_atra": [
      0.1,
      0
    ],
    "e_shot": [
      0.1,
      0.07
    ],
    "e_sprite": [
      0.17,
      0
    ],
    "e_draw": [
      0.04,
      0.31
    ],
    "e_mage": [
      0.09,
      0
    ],
    "e_march": [
      0.18,
      0
    ],
    "e_storm": [
      0.06,
      0.04
    ],
    "e_eternal": [
      0.09,
      0.01
    ],
    "e_pray": [
      0.19,
      0.07
    ],
    "e_tuner": [
      0.16,
      0
    ],
    "e_twin": [
      0.18,
      0
    ],
    "e_verna": [
      0.1,
      0
    ],
    "e_blade": [
      0.19,
      0
    ],
    "e_raider": [
      0.18,
      0
    ],
    "e_reverse": [
      0,
      0.09
    ],
    "e_page": [
      0.17,
      0
    ],
    "e_slash": [
      0.22,
      0.07
    ],
    "e_break": [
      0.06,
      0.03
    ],
    "e_guard": [
      0.27,
      0
    ],
    "e_colossus": [
      0.21,
      0
    ],
    "x_mirea": [
      0.14,
      0
    ],
    "x_seer": [
      0.2,
      0
    ],
    "x_decoy": [
      0,
      0.15
    ],
    "x_gust": [
      0.29,
      0.01
    ],
    "x_oblivion": [
      0.01,
      0.2
    ],
    "x_ram": [
      0.17,
      0
    ],
    "x_usurper": [
      0.09,
      0
    ],
    "x_sentry": [
      0.18,
      0
    ]
  },
  "decks": [
    "均衡の刻",
    "秒針突撃",
    "永劫の城塞",
    "予言の書架",
    "残響",
    "急襲",
    "均衡+",
    "城塞+",
    "記憶の書庫",
    "簒奪の衛士"
  ],
  "matrix": {
    "均衡の刻": [
      46,
      58,
      52,
      51,
      31,
      75,
      53,
      32,
      56,
      66
    ],
    "秒針突撃": [
      53,
      50,
      39,
      63,
      48,
      43,
      48,
      46,
      70,
      58
    ],
    "永劫の城塞": [
      56,
      59,
      47,
      61,
      51,
      59,
      59,
      58,
      55,
      75
    ],
    "予言の書架": [
      40,
      36,
      36,
      52,
      63,
      58,
      55,
      41,
      66,
      55
    ],
    "残響": [
      56,
      53,
      50,
      55,
      58,
      61,
      50,
      61,
      51,
      41
    ],
    "急襲": [
      38,
      38,
      36,
      56,
      48,
      52,
      36,
      46,
      59,
      42
    ],
    "均衡+": [
      63,
      42,
      55,
      53,
      48,
      66,
      59,
      56,
      64,
      57
    ],
    "城塞+": [
      60,
      45,
      49,
      62,
      50,
      58,
      52,
      53,
      45,
      55
    ],
    "記憶の書庫": [
      45,
      42,
      49,
      36,
      50,
      39,
      45,
      63,
      48,
      42
    ],
    "簒奪の衛士": [
      52,
      47,
      41,
      48,
      63,
      58,
      38,
      34,
      61,
      63
    ]
  }
};
