/* Environment round robin for the wiki: `npm run meta -- [--games 6] [--level expert++] [--jobs 2]`
 *
 * Every deck of src/sim/metaDecks.ts plays every other one with the given rated AI strength on both sides (the
 * strongest, 超つよい＋＋, by default). Results are saved in logs/meta-results.json as they come in, so a run that
 * stops can simply be started again and continues. When all games are in, src/wiki/meta.ts is written: the deck
 * ranking, the matchup table and, for every card, how much better a deck did in the games where the card was used
 * than that deck's own average ("影響").
 * About 25 s per game on one core: 16 decks × 6 games ≈ 720 games ≈ 2.5 h on 2 cores.
 */
import { fork } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { chooseActionSpec } from '../core/ai';
import { actor, apply, createGame, mulberry32, type PlayerIndex } from '../core/engine';
import { foeById } from '../meta/rating';
import { META_DECKS } from './metaDecks';

const proc = process as unknown as { argv: string[]; execArgv: string[]; on(ev: 'message', f: (m: Job | 'bye') => void): void; send(m: unknown): void; exit(code: number): never };
interface Job { a: number; b: number; i: number; level: string }
interface Res { a: number; b: number; i: number; sa: number; reason: string; usedA: string[]; usedB: string[]; acts: number; ms: number }
const OUT = 'logs/meta-results.json';

function play(j: Job): Res {
  const t = Date.now(), spec = foeById(j.level)!.spec;
  const seed = 70000 + j.a * 1000 + j.b * 37 + j.i;
  const sa = (j.i % 2) as PlayerIndex; // deck a's seat
  const A = META_DECKS[j.a].cards, B = META_DECKS[j.b].cards;
  const { state } = createGame(sa === 0 ? [A, B] : [B, A], seed, (Math.floor(j.i / 2) % 2) as PlayerIndex);
  const r = mulberry32(seed);
  const used: [Set<string>, Set<string>] = [new Set(), new Set()];
  let acts = 0;
  for (; !state.over && acts < 600; acts++) {
    const pi = actor(state);
    if (pi === -1) break;
    for (const e of apply(state, chooseActionSpec(state, pi, spec, r))) {
      if (e.e === 'summon' && e.fromHand >= 0) used[e.pi].add(e.unit.card);
      if (e.e === 'cast' || e.e === 'reserve') used[e.pi].add(e.card);
    }
  }
  const w = state.over?.winner ?? -1;
  return { a: j.a, b: j.b, i: j.i, sa: w === -1 ? 0.5 : w === sa ? 1 : 0, reason: state.over?.reason ?? 'none', usedA: [...used[sa]], usedB: [...used[(1 - sa) as PlayerIndex]], acts, ms: Date.now() - t };
}

function writeWiki(R: Res[], per: number, level: string) {
  const N = META_DECKS.length;
  const W = Array.from({ length: N }, () => Array(N).fill(0) as number[]), G = Array.from({ length: N }, () => Array(N).fill(0) as number[]);
  for (const r of R) { W[r.a][r.b] += r.sa; W[r.b][r.a] += 1 - r.sa; G[r.a][r.b]++; G[r.b][r.a]++; }
  const avg = META_DECKS.map((_, d) => { let s = 0, k = 0; for (let o = 0; o < N; o++) if (o !== d && G[d][o]) { s += W[d][o] / G[d][o]; k++; } return k ? s / k : 0; });
  const card: Record<string, [number, number, number]> = {}; // [sum of (points − deck average), times used, times in deck]
  for (const r of R) for (const [d, usedCards, pts] of [[r.a, r.usedA, r.sa], [r.b, r.usedB, 1 - r.sa]] as [number, string[], number][]) {
    for (const c of new Set(META_DECKS[d].cards)) (card[c] ??= [0, 0, 0])[2]++;
    for (const c of usedCards) { const x = (card[c] ??= [0, 0, 0]); x[0] += pts - avg[d]; x[1]++; }
  }
  const meta = {
    date: new Date().toISOString().slice(0, 10), games: R.length, perPair: per, level,
    decks: META_DECKS.map((d, i) => ({ id: d.id, win: Math.round(1000 * avg[i]) / 10 })),
    matrix: META_DECKS.map((_, d) => META_DECKS.map((__, o) => (d === o || !G[d][o] ? -1 : Math.round((100 * W[d][o]) / G[d][o])))),
    cards: Object.fromEntries(Object.entries(card).map(([c, [s, u, n]]) => [c, [u ? Math.round((1000 * s) / u) / 10 : 0, u, n]])),
  };
  writeFileSync('src/wiki/meta.ts', `/* Generated by \`npm run meta\` — do not edit by hand. 環境デッキの総当たり（両者とも同じ強さのAI）。 */
export const META: {
  date: string; games: number; perPair: number; level: string;
  /** In the order of META_DECKS; win = average win % against the other decks. */
  decks: { id: string; win: number }[];
  /** matrix[row][col] = win % of the row deck against the column deck (−1 on the diagonal). */
  matrix: number[][];
  /** card id → [影響 (win % when used minus the deck's average), games used, games in a deck]. */
  cards: Record<string, [number, number, number]>;
} = ${JSON.stringify(meta)};
`);
  console.log(`→ src/wiki/meta.ts（${R.length}試合）`);
}

if (proc.argv[2] === '--worker') {
  proc.on('message', (m) => { if (m === 'bye') proc.exit(0); else proc.send(play(m)); });
} else void (async () => {
  const args = proc.argv.slice(2);
  const opt = (k: string, d: string) => { const i = args.indexOf(k); return i < 0 ? d : args[i + 1]; };
  const per = +opt('--games', '6'), level = opt('--level', 'expert++'), jobsN = +opt('--jobs', '2');
  if (!foeById(level)) { console.error(`知らない強さ: ${level}`); proc.exit(1); }
  mkdirSync('logs', { recursive: true });
  const done: Res[] = existsSync(OUT) ? JSON.parse(readFileSync(OUT, 'utf8')) : [];
  const have = new Set(done.map((x) => `${x.a}-${x.b}-${x.i}`));
  const jobs: Job[] = [];
  for (let i = 0; i < per; i++) for (let a = 0; a < META_DECKS.length; a++) for (let b = a + 1; b < META_DECKS.length; b++) if (!have.has(`${a}-${b}-${i}`)) jobs.push({ a, b, i, level });
  console.log(`残り${jobs.length}試合（${META_DECKS.length}デッキ×各${per}戦、AI ${level}、${jobsN}並列）`);
  let next = 0, n = 0;
  const t0 = Date.now();
  await Promise.all(Array.from({ length: Math.min(jobsN, jobs.length) }, () => new Promise<void>((res) => {
    const w = fork(fileURLToPath(import.meta.url), ['--worker'], { execArgv: proc.execArgv });
    const feed = () => { if (next < jobs.length) w.send(jobs[next++]); else { w.send('bye'); res(); } };
    w.on('message', (m: Res) => {
      done.push(m); n++;
      if (n % 10 === 0 || n === jobs.length) { writeFileSync(OUT, JSON.stringify(done)); console.log(`${n}/${jobs.length}（${Math.round((Date.now() - t0) / 60000)}分）`); }
      feed();
    });
    feed();
  })));
  writeFileSync(OUT, JSON.stringify(done));
  writeWiki(done.filter((r) => r.i < per), per, level);
})();
