/* Writes the numbers shown on the strategy wiki: `npm run wiki:stats -- [games]`.
 * Plays every deck (基本4＋第1弾入り4) against every other with the normal AI and saves
 * per-card win rates, per-card usage and the deck matchup table to src/wiki/stats.ts. */
import { writeFileSync } from 'node:fs';
import { chooseAction } from '../core/ai';
import { PRESET_DECKS } from '../core/decks';
import { actor, apply, createGame, mulberry32, type PlayerIndex } from '../core/engine';
import { PACK_TEST_DECKS } from './packDecks';

const N = +(process.argv[2] ?? 6400);
const DECKS = [...PRESET_DECKS, ...PACK_TEST_DECKS];
const per = Math.max(2, Math.round(N / DECKS.length ** 2));

const cardWin: Record<string, [number, number]> = {};
const use: Record<string, [number, number]> = {};
const matrix: Record<string, number[]> = {};
let games = 0;

function play(a: string[], b: string[], seed: number): PlayerIndex | -1 {
  const first = (seed % 2) as PlayerIndex;
  const { state } = createGame([a, b], seed, first);
  const rand = mulberry32(seed * 7 + 1);
  const played: [Set<string>, Set<string>] = [new Set(), new Set()];
  for (let guard = 0; !state.over && guard < 400; guard++) {
    const pi = actor(state);
    if (pi === -1) break;
    for (const e of apply(state, chooseAction(state, pi, 'normal', rand))) {
      if (e.e === 'summon' && e.fromHand >= 0) { played[e.pi].add(e.unit.card); (use[e.unit.card] ??= [0, 0])[0]++; }
      if (e.e === 'cast') { played[e.pi].add(e.card); (use[e.card] ??= [0, 0])[0]++; }
      if (e.e === 'reserve') { played[e.pi].add(e.card); (use[e.card] ??= [0, 0])[1]++; }
    }
  }
  games++;
  const w = state.over?.winner ?? -1;
  for (const pi of [0, 1] as PlayerIndex[]) for (const c of played[pi]) {
    const r = (cardWin[c] ??= [0, 0]);
    r[1]++;
    if (w === pi) r[0]++; else if (w === -1) r[0] += 0.5;
  }
  return w;
}

let seed = 1;
for (const A of DECKS) {
  matrix[A.name] = [];
  for (const B of DECKS) {
    let aw = 0;
    for (let i = 0; i < per; i++) { const w = play(A.cards, B.cards, seed++); aw += w === 0 ? 1 : w === -1 ? 0.5 : 0; }
    matrix[A.name].push(Math.round((aw / per) * 100));
  }
}

const r2 = (x: number) => Math.round(x * 100) / 100;
const stats = {
  date: new Date().toISOString().slice(0, 10),
  games,
  perPair: per,
  /** Win % of the games in which the card was played (at least 30 games). */
  win: Object.fromEntries(Object.entries(cardWin).filter(([, [, n]]) => n >= 30).map(([k, [w, n]]) => [k, Math.round((w / n) * 100)])),
  /** Times per game: [used right away, reserved]. */
  use: Object.fromEntries(Object.entries(use).map(([k, [u, r]]) => [k, [r2(u / games), r2(r / games)]])),
  decks: DECKS.map((d) => d.name),
  matrix,
};
const out = new URL('../wiki/stats.ts', import.meta.url);
writeFileSync(out, `/* Generated by \`npm run wiki:stats\` — do not edit by hand. AI「ふつう」同士の対戦結果。 */\nexport const STATS: {\n  date: string; games: number; perPair: number;\n  win: Record<string, number>; use: Record<string, [number, number]>;\n  decks: string[]; matrix: Record<string, number[]>;\n} = ${JSON.stringify(stats, null, 2)};\n`);
console.log(`${games} games → src/wiki/stats.ts`);
